server:
  port: 8080

room:
  #tfs服务器地址
  tfsServer: http://10.99.11.229:9890

spring:
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/views/
  datasource:
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

      ######Druid监控配置######
      #配置WebStatFilter
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #配置StatViewServlet
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      #spring监听配置
      aop-patterns: 'com.wtown.suggest.service.*'

      ######多数据源配置######
      one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/report?characterEncoding=utf8&useSSL=true&serverTimezone=PRC&nullNamePatternMatchesAll=true
        username: root
        password: 123456

  aop:
    proxy-target-class: true